[package]
name = "todiff"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]

[dependencies]
chrono = "0.4.0"
clap = "2.31.1"
todo-txt = { git = "https://github.com/Ekleog/todo-txt" }
strsim = "0.7.0"
multiset = "0.0.4"
